kind: pipeline
type: docker
name: integration

steps:
    - name: build
      image: mcr.microsoft.com/dotnet/sdk
      commands:
        - dotnet build
      
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands: 
      - dotnet sonarscanner begin /k:"easv-devops_LasseDrone_AY19HJkpEVvRW2O60D3-" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_64e459f022742d9ff0c4c7129892c337e90e0e76"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.token="sqp_64e459f022742d9ff0c4c7129892c337e90e0e76"
